```     [ Querys para Base de dados | Livros ]
    INSERT INTO livros (nome, ano_publicacao, genero) VALUES
    ('Dom Casmurro', 1899, 'romance'),
    ('O Pequeno Príncipe', 1943, 'fantasia'),
    ('1984', 1949, 'ficcao'),
    ('A Revolução dos Bichos', 1945, 'ficcao'),
    ('O Hobbit', 1937, 'fantasia'),
    ('Harry Potter e a Pedra Filosofal', 1997, 'fantasia'),
    ('Senhor dos Aneis', 1954, 'fantasia'),
    ('O Codigo Da Vinci', 2003, 'misterio'),
    ('Crepusculo', 2005, 'romance'),
    ('Jogos Vorazes', 2008, 'aventura'),
    ('It - A Coisa', 1986, 'terror'),
    ('Dracula', 1897, 'terror'),
    ('Frankenstein', 1818, 'terror'),
    ('A Culpa é das Estrelas', 2012, 'romance'),
    ('Extraordinario', 2012, 'drama'),
    ('O Alquimista', 1988, 'ficcao'),
    ('Capitaes da Areia', 1937, 'drama'),
    ('Memorias Postumas de Bras Cubas', 1881, 'romance'),
    ('A Cabana', 2007, 'drama'),
    ('O Diario de Anne Frank', 1947, 'biografia'),
    ('Percy Jackson', 2005, 'fantasia'),
    ('Maze Runner', 2009, 'ficcao'),
    ('Duna', 1965, 'ficcao'),
    ('O Iluminado', 1977, 'terror'),
    ('Sherlock Holmes', 1892, 'misterio'),
    ('A Menina que Roubava Livros', 2005, 'drama'),
    ('As Cronicas de Narnia', 1950, 'fantasia'),
    ('O Senhor das Moscas', 1954, 'drama'),
    ('Orgulho e Preconceito', 1813, 'romance'),
    ('A Metamorfose', 1915, 'ficcao'),
    ('O Poder do Habito', 2012, 'drama'),
    ('Pai Rico Pai Pobre', 1997, 'drama'),
    ('Mindset', 2006, 'drama'),
    ('O Milagre da Manha', 2012, 'drama'),
    ('Sapiens', 2011, 'historia'),
    ('A Arte da Guerra', 500, 'historia'),
    ('O Nome do Vento', 2007, 'fantasia'),
    ('A Garota no Trem', 2015, 'misterio'),
    ('O Codigo Limpo', 2008, 'tecnologia'),
    ('Use a Cabeca Java', 2003, 'tecnologia'),
    ('Introducao ao MySQL', 2015, 'tecnologia'),
    ('PHP para Iniciantes', 2018, 'tecnologia'),
    ('Banco de Dados Avancado', 2020, 'tecnologia'),
    ('Aprendendo JavaScript', 2019, 'tecnologia'),
    ('Estruturas de Dados', 2017, 'tecnologia'),
    ('Algoritmos Descomplicados', 2016, 'tecnologia'),
    ('Redes de Computadores', 2014, 'tecnologia'),
    ('Engenharia de Software', 2013, 'tecnologia'),
    ('Inteligencia Artificial', 2021, 'tecnologia'),
    ('Cyberseguranca Moderna', 2022, 'tecnologia');
```

